<?php

namespace DoctrineProxies\__CG__\Manager\Domain\Model\Manager;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sales extends \Manager\Domain\Model\Manager\Sales implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'manager', 'id', 'contractTerminated', 'createdTime', 'contractTerminatedTime', 'accountInfo', 'type', 'customerAssignments', 'activeCustomerAssignmentCount', 'multipleCustomerAssignmentReceivedBySalesEvent', 'recordedEvents', 'childrenContainEvents'];
        }

        return ['__isInitialized__', 'manager', 'id', 'contractTerminated', 'createdTime', 'contractTerminatedTime', 'accountInfo', 'type', 'customerAssignments', 'activeCustomerAssignmentCount', 'multipleCustomerAssignmentReceivedBySalesEvent', 'recordedEvents', 'childrenContainEvents'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sales $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function isInHouseSales(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInHouseSales', []);

        return parent::isInHouseSales();
    }

    /**
     * {@inheritDoc}
     */
    public function assertActive(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'assertActive', []);

        parent::assertActive();
    }

    /**
     * {@inheritDoc}
     */
    public function belongsToManager(\Manager\Domain\Model\Manager $manager): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'belongsToManager', [$manager]);

        return parent::belongsToManager($manager);
    }

    /**
     * {@inheritDoc}
     */
    public function assertBelongsToManager(\Manager\Domain\Model\Manager $manager): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'assertBelongsToManager', [$manager]);

        parent::assertBelongsToManager($manager);
    }

    /**
     * {@inheritDoc}
     */
    public function calculateActiveCustomerAssignmentsCount(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateActiveCustomerAssignmentsCount', []);

        return parent::calculateActiveCustomerAssignmentsCount();
    }

    /**
     * {@inheritDoc}
     */
    public function receiveCustomerAssignment(string $id, \Manager\Domain\DependencyModel\Customer $customer, ?\Manager\Domain\DependencyModel\CustomerJourney $customerJourney): ?\Manager\Domain\Model\Manager\Sales\CustomerAssignment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'receiveCustomerAssignment', [$id, $customer, $customerJourney]);

        return parent::receiveCustomerAssignment($id, $customer, $customerJourney);
    }

    /**
     * {@inheritDoc}
     */
    public function pullRecordedEvents(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'pullRecordedEvents', []);

        return parent::pullRecordedEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function recordEvent(\Resources\Event\EventInterface $event): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'recordEvent', [$event]);

        parent::recordEvent($event);
    }

}
