<?php

namespace DoctrineProxies\__CG__\Sales\Domain\Model\Sales;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CustomerAssignment extends \Sales\Domain\Model\Sales\CustomerAssignment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'sales', 'customer', 'customerJourney', 'id', 'status', 'createdTime', 'closingRequests', 'recycleRequests', 'salesActivitySchedules', 'customerAssignmentJourneys', 'recordedEvents', 'childrenContainEvents'];
        }

        return ['__isInitialized__', 'sales', 'customer', 'customerJourney', 'id', 'status', 'createdTime', 'closingRequests', 'recycleRequests', 'salesActivitySchedules', 'customerAssignmentJourneys', 'recordedEvents', 'childrenContainEvents'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CustomerAssignment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getStatus(): \Shared\Domain\Enum\CustomerAssignmentStatus
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function updateJourney(\Sales\Domain\DependencyModel\CustomerJourney $customerJourney): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateJourney', [$customerJourney]);

        parent::updateJourney($customerJourney);
    }

    /**
     * {@inheritDoc}
     */
    public function updateCustomer(?\Sales\Domain\DependencyModel\Province\City $city, \Sales\Domain\DependencyModel\CustomerData $customerData): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateCustomer', [$city, $customerData]);

        parent::updateCustomer($city, $customerData);
    }

    /**
     * {@inheritDoc}
     */
    public function SubmitCustomerVerificationReport(\Sales\Domain\DependencyModel\CustomerVerification $customerVerification, \Sales\Domain\DependencyModel\Customer\VerificationReportData $verificationReportData): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'SubmitCustomerVerificationReport', [$customerVerification, $verificationReportData]);

        parent::SubmitCustomerVerificationReport($customerVerification, $verificationReportData);
    }

    /**
     * {@inheritDoc}
     */
    public function assertBelongsToSales(\Sales\Domain\Model\Sales $sales): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'assertBelongsToSales', [$sales]);

        parent::assertBelongsToSales($sales);
    }

    /**
     * {@inheritDoc}
     */
    public function assertActive(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'assertActive', []);

        parent::assertActive();
    }

    /**
     * {@inheritDoc}
     */
    public function submitSalesActivitySchedule(\Sales\Domain\DependencyModel\SalesActivity $salesActivity, \Sales\Domain\Model\Sales\CustomerAssignment\SalesActivityScheduleData $scheduledSalesActivityData): \Sales\Domain\Model\Sales\CustomerAssignment\SalesActivitySchedule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'submitSalesActivitySchedule', [$salesActivity, $scheduledSalesActivityData]);

        return parent::submitSalesActivitySchedule($salesActivity, $scheduledSalesActivityData);
    }

    /**
     * {@inheritDoc}
     */
    public function submitClosingRequest(\Sales\Domain\Model\Sales\CustomerAssignment\ClosingRequestData $closingRequestData): \Sales\Domain\Model\Sales\CustomerAssignment\ClosingRequest
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'submitClosingRequest', [$closingRequestData]);

        return parent::submitClosingRequest($closingRequestData);
    }

    /**
     * {@inheritDoc}
     */
    public function submitRecycleRequest(\Sales\Domain\Model\Sales\CustomerAssignment\RecycleRequestData $recycleRequestData): \Sales\Domain\Model\Sales\CustomerAssignment\RecycleRequest
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'submitRecycleRequest', [$recycleRequestData]);

        return parent::submitRecycleRequest($recycleRequestData);
    }

    /**
     * {@inheritDoc}
     */
    public function addUpcomingScheduleToSchedulerService(\Sales\Domain\Service\SalesActivitySchedulerService $service): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUpcomingScheduleToSchedulerService', [$service]);

        parent::addUpcomingScheduleToSchedulerService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function initiateSalesActivitySchedule(\Sales\Domain\DependencyModel\SalesActivity $initialSalesActivity, \Sales\Domain\Service\SalesActivitySchedulerService $schedulerService): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initiateSalesActivitySchedule', [$initialSalesActivity, $schedulerService]);

        parent::initiateSalesActivitySchedule($initialSalesActivity, $schedulerService);
    }

    /**
     * {@inheritDoc}
     */
    public function pullRecordedEvents(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'pullRecordedEvents', []);

        return parent::pullRecordedEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function recordEvent(\Resources\Event\EventInterface $event): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'recordEvent', [$event]);

        parent::recordEvent($event);
    }

}
