<?php

namespace Shared\Domain\Enum;

enum MetricType: string
{

    case SALES_ACTIVITY_REPORT = 'SALES_ACTIVITY_REPORT';
    case APPROVED_CLOSING_REQUEST = 'APPROVED_CLOSING_REQUEST';
    case SUCCESSFULL_GREETING = 'SUCCESSFULL_GREETING';
    case COMPLETED_FACT_FINDING = 'COMPLETED_FACT_FINDING';
}
